version: "3.8"

services:
  app:
    container_name: app
    restart: always
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    depends_on:
      - app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
